"""empty message

Revision ID: 3fac77361324
Revises: 07d9586c45ee
Create Date: 2023-04-19 05:56:54.448727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fac77361324'
down_revision = '07d9586c45ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('problem_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_solution_problem_id_problem'), 'problem', ['problem_id'], ['id'])
        batch_op.drop_column('solution_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_solution_problem_id_problem'), type_='foreignkey')
        batch_op.drop_column('problem_id')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
