"""title and description added to problem table.

Revision ID: d81b762e2e47
Revises: fe1de29f71b9
Create Date: 2023-04-10 02:37:34.304312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81b762e2e47'
down_revision = 'fe1de29f71b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))
        batch_op.drop_column('contents')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contents', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
