"""empty message

Revision ID: fa26f58e273b
Revises: 0e660dca1dd8
Create Date: 2023-04-19 15:28:44.796067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa26f58e273b'
down_revision = '0e660dca1dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_constraint('fk_solution_problem_id_problem', type_='foreignkey')
        batch_op.drop_column('problem_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_solution_problem_id_problem', 'problem', ['problem_id'], ['id'])

    # ### end Alembic commands ###
